/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.yousi.ddz;

 public final class RR {
     public static final class attr {
     }
     public static final class color {
         public static final int gray=0x7f050001;
         public static final int white=0x7f050000;
     }
     public static final class dimen {
         /**  Default screen margins, per the Android Design guidelines.
          */
         public static final int activity_horizontal_margin=0x7f060000;
         public static final int activity_vertical_margin=0x7f060001;
     }
     public static final class drawable {
         public static final int app_icon=0x7f020000;
         public static final int background_splash=0x7f020001;
         public static final int notify_icon_small=0x7f020002;
     }
     public static final class layout {
         public static final int activity_main=0x7f040000;
     }
     public static final class mipmap {
         public static final int splash=0x7f030000;
     }
     public static final class string {
         public static final int app_name=0x7f070000;
         public static final int app_name2=0x7f070001;
         public static final int pay_result_tip=0x7f070002;
     }
     public static final class style {
         public static final int SplashTheme=0x7f080001;
         public static final int UnityThemeSelector=0x7f080000;
     }
 }
