//
// EffectScanner.cs
//
// Author:
//      duwenjie
//
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using UnityEditor;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System;
using LBoot;
using System.Linq;
using System.Text.RegularExpressions;
using LitJson;
using System.Text;

public class EffectScanner
{
    public EffectScanner()
    {
    }

    public void ScanPrefab(string name, GameObject prefab)
    {
        var go = GameObject.Instantiate(prefab);
        // LogUtil.Warn("---- name:" + name);

        var fvpr = go.GetComponent<FVParticleRoot>();
        if (fvpr == null)
        {
            LogUtil.Error(name);
            //return;
        }
        var ps = go.GetComponentsInChildren<ParticleSystem>();
        foreach (Component p in ps)
        {
            var tmpgo = p.gameObject;
            var fvps = go.GetComponent<FVParticleScaling>();
            var curname = p.transform.name;
            // LogUtil.Warn("curname:" + curname);
            if (fvpr == null)
            {
                LogUtil.Error(name + " : " + curname);
            }
        }

        GameObject.DestroyImmediate(go);
    }

    public void ScanParticleSimSpace(string name, GameObject prefab)
    {
        var go = GameObject.Instantiate(prefab);

        ParticleSystem[] ps = go.GetComponentsInChildren<ParticleSystem>();
        foreach (ParticleSystem p in ps)
        {
            var tmpgo = p.gameObject;
            var curname = p.transform.name;
            if (p.simulationSpace != ParticleSystemSimulationSpace.Local)
            {
                LogUtil.Error(name + " : " + curname);
            }
        }

        GameObject.DestroyImmediate(go);
    }
}
