//
// LBootAppBehaviour.cs
//
// Author:
//       duwenjie
//

//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using LuaInterface;
using System.Collections;

namespace LBoot
{
    /// <summary>
    /// LBootAppBeahviour
    /// This behaviour provides necessary integration with other components
    /// </summary>
    //[RequireComponent(typeof(SchedulerBehaviour))]
    [RequireComponent(typeof(GlobalUpdateBehaviour))]
    [RequireComponent(typeof(UnityThreadHelper))]
    [RequireComponent(typeof(UnityEngine.EventSystems.StandaloneInputModule))]
    [RequireComponent(typeof(UnityEngine.EventSystems.TouchInputModule))]
    [RequireComponent(typeof(UnityEngine.EventSystems.EventSystem))]
    public class LBootAppBehaviour : AppLifecycleBehaviour
    {
        // Respond to UnitySendMessage

#if UNITY_ANDROID && ! UNITY_EDITOR
        public void invokeLuaCallback(string message)
        {
            int callback = Convert.ToInt32(message.Substring(0, 10));
            string result = message.Substring(10);

            LuaDLL.CCLuaJavaBridge_callLuaFunctionById(callback, result);
            LuaDLL.CCLuaJavaBridge_releaseLuaFunctionById(callback);
        }

        public void invokeLuaCallbackNoRelease(string message)
        {
            int callback = Convert.ToInt32(message.Substring(0, 10));
            string result = message.Substring(10);
            
            LuaDLL.CCLuaJavaBridge_callLuaFunctionById(callback, result);
        }

        public void releaseLuaCallback(string message)
        {
            int callback = Convert.ToInt32(message.Substring(0, 10));
            string result = message.Substring(10);

            LuaDLL.CCLuaJavaBridge_releaseLuaFunctionById(callback);
        }
#endif // UNITY_ANDROID

    }
}

