//
// FileUtilsAndroid.cs
//
// Author:
//       duwenjie
//

//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// #define PROFILE_FILE

#if UNITY_ANDROID

using System;
using System.IO;
using System.Runtime.InteropServices;
using UnityEngine;

namespace LBoot
{
    /// <summary>
    /// FileUtilsAndroid
    /// </summary>
    public class FileUtilsAndroid
    {
        const string DLLNAME = "slua";
        
        [DllImport(DLLNAME, CallingConvention = CallingConvention.Cdecl)]
        private static extern int isFileExistsInAppJarFile(string path);

        [DllImport(DLLNAME, CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr readDataFromAppJarFile(string path, long readOffset, long readSize);
        
        [DllImport(DLLNAME, CallingConvention = CallingConvention.Cdecl)]
        private static extern void freeData(IntPtr L);

        [DllImport(DLLNAME, CallingConvention = CallingConvention.Cdecl)]
        private static extern int copyDataFromAppJarFile(string srcfile, string dstfile, long readOffset, long readSize);

        public static bool IsFileExistsInAppJar(string path)
        {
#if PROFILE_FILE
            Profiler.BeginSample("FileUtilsAndroid.IsFileExistsInAppJar");
#endif
            if (isFileExistsInAppJarFile(path) == 1)
            {
#if PROFILE_FILE
            Profiler.EndSample();
#endif
                return true;
            }
            else
            {
//                LogUtil.Debug("FileUtilsAndroid: file not exists in jar! " + path);
#if PROFILE_FILE
            Profiler.EndSample();
#endif
                return false;
            }
        }

        // TODO avoid coping data from C heap to managed heap
        //      maybe optimize by getting file length and preallocate in C#
        public static byte [] ReadDataFromAppJar(string path, long readOffset, long readSize, out long bytesRead)
        {
#if PROFILE_FILE
            Profiler.BeginSample("FileUtilsAndroid.ReadDataFromAppJar");
#endif
            IntPtr L = IntPtr.Zero;

            try 
            {
                L = readDataFromAppJarFile(path, readOffset, readSize);
                if (L != IntPtr.Zero)
                {
                    long size = Marshal.ReadInt64(L);
                    LogUtil.Debug("read from jar, size is " + size + 
                        " readOffset is " + readOffset + " readSize is " + readSize);
                    byte [] data = new byte[size];
                    Marshal.Copy(new IntPtr(L.ToInt64() + sizeof(Int64)), data, 0, (int) size);
                    bytesRead = size;
#if PROFILE_FILE
                    Profiler.EndSample();
#endif
                    return data;
                }
                else
                {
                    LogUtil.Error("FileUtilsAndroid: read from jar failed! " + path);
                    bytesRead = 0;
#if PROFILE_FILE
                    Profiler.EndSample();
#endif
                    return null;
                }
            }
            finally
            {
                if (L != IntPtr.Zero)
                {
                    freeData(L);
                }
            }
        }

        public static bool CopyFileFromAppJar(string srcfile, string dstfile, bool overwrite)
        {
            if (! overwrite && File.Exists(dstfile)) 
            {
                LogUtil.Debug("FileUtilsAndroid: copyDataFromAppJarFile dstfile already exists! " + dstfile);
                return false;
            }

            int res = copyDataFromAppJarFile(srcfile, dstfile, 0, 0);
            if (res == 0)
            {
                return true;
            }
            else
            {
                LogUtil.Error("FileUtilsAndroid: copyDataFromAppJarFile failed! res=" + res);
                return false;
            }
        }
    }
}

#endif // UNITY_ANDROID